export default [
  {
    country: "Côte d'Ivoire",
    code: "384"
  }, {
    country: 'Saint-Barthélemy',
    code: "652"
  }, {
    country: 'Réunion',
    code: "638"
  }, {
    country: 'Afghanistan',
    code: "004"
  }, {
    country: 'AlandIslands',
    code: "248"
  }, {
    country: 'Albania',
    code: "008"
  }, {
    country: 'Algeria',
    code: "012"
  }, {
    country: 'AmericanSamoa',
    code: "016"
  }, {
    country: 'Andorra',
    code: "020"
  }, {
    country: 'Angola',
    code: "024"
  }, {
    country: 'Anguilla',
    code: "660"
  }, {
    country: 'Antarctica',
    code: "010"
  }, {
    country: 'AntiguaandBarbuda',
    code: "028"
  }, {
    country: 'Argentina',
    code: "032"
  }, {
    country: 'Armenia',
    code: "051"
  }, {
    country: 'Aruba',
    code: "533"
  }, {
    country: 'Australia',
    code: "036"
  }, {
    country: 'Austria',
    code: "040"
  }, {
    country: 'Azerbaijan',
    code: "031"
  }, {
    country: 'Bahamas',
    code: "044"
  }, {
    country: 'Bahrain',
    code: "048"
  }, {
    country: 'Bangladesh',
    code: "050"
  }, {
    country: 'Barbados',
    code: "052"
  }, {
    country: 'Belarus',
    code: "112"
  }, {
    country: 'Belgium',
    code: "056"
  }, {
    country: 'Belize',
    code: "084"
  }, {
    country: 'Benin',
    code: "204"
  }, {
    country: 'Bermuda',
    code: "060"
  }, {
    country: 'Bhutan',
    code: "064"
  }, {
    country: 'Bolivia',
    code: "068"
  }, {
    country: 'BosniaandHerzegovina',
    code: "070"
  }, {
    country: 'Botswana',
    code: "072"
  }, {
    country: 'BouvetIsland',
    code: "074"
  }, {
    country: 'Brazil',
    code: "076"
  }, {
    country: 'BritishVirginIslands',
    code: "092"
  }, {
    country: 'BritishIndianOceanTerritory',
    code: "086"
  }, {
    country: 'BruneiDarussalam',
    code: "096"
  }, {
    country: 'Bulgaria',
    code: "100"
  }, {
    country: 'BurkinaFaso',
    code: "854"
  }, {
    country: 'Burundi',
    code: "108"
  }, {
    country: 'Cambodia',
    code: "116"
  }, {
    country: 'Cameroon',
    code: "120"
  }, {
    country: 'Canada',
    code: "124"
  }, {
    country: 'CapeVerde',
    code: "132"
  }, {
    country: 'CaymanIslands',
    code: "136"
  }, {
    country: 'CentralAfricanRepublic',
    code: "140"
  }, {
    country: 'Chad',
    code: "148"
  }, {
    country: 'Chile',
    code: "152"
  }, {
    country: 'China',
    code: "156"
  }, {
    country: 'HongKong',
    code: "344"
  }, {
    country: 'Macao',
    code: "446"
  }, {
    country: 'ChristmasIsland',
    code: "162"
  }, {
    country: 'Cocos(Keeling)Islands',
    code: "166"
  }, {
    country: 'Colombia',
    code: "170"
  }, {
    country: 'Comoros',
    code: "174"
  }, {
    country: 'Congo',
    code: "178"
  }, {
    country: 'Congo',
    code: "180"
  }, {
    country: 'CookIslands',
    code: "184"
  }, {
    country: 'CostaRica',
    code: "188"
  }, {
    country: 'Croatia',
    code: "191"
  }, {
    country: 'Cuba',
    code: "192"
  }, {
    country: 'Cyprus',
    code: "196"
  }, {
    country: 'CzechRepublic',
    code: "203"
  }, {
    country: 'Denmark',
    code: "208"
  }, {
    country: 'Djibouti',
    code: "262"
  }, {
    country: 'Dominica',
    code: "212"
  }, {
    country: 'DominicanRepublic',
    code: "214"
  }, {
    country: 'Ecuador',
    code: "218"
  }, {
    country: 'Egypt',
    code: "818"
  }, {
    country: 'ElSalvador',
    code: "222"
  }, {
    country: 'EquatorialGuinea',
    code: "226"
  }, {
    country: 'Eritrea',
    code: "232"
  }, {
    country: 'Estonia',
    code: "233"
  }, {
    country: 'Ethiopia',
    code: "231"
  }, {
    country: 'FalklandIslands(Malvinas)',
    code: "238"
  }, {
    country: 'FaroeIslands',
    code: "234"
  }, {
    country: 'Fiji',
    code: "242"
  }, {
    country: 'Finland',
    code: "246"
  }, {
    country: 'France',
    code: "250"
  }, {
    country: 'FrenchGuiana',
    code: "254"
  }, {
    country: 'FrenchPolynesia',
    code: "258"
  }, {
    country: 'FrenchSouthernTerritories',
    code: "260"
  }, {
    country: 'Gabon',
    code: "266"
  }, {
    country: 'Gambia',
    code: "270"
  }, {
    country: 'Georgia',
    code: "268"
  }, {
    country: 'Germany',
    code: "276"
  }, {
    country: 'Ghana',
    code: "288"
  }, {
    country: 'Gibraltar',
    code: "292"
  }, {
    country: 'Greece',
    code: "300"
  }, {
    country: 'Greenland',
    code: "304"
  }, {
    country: 'Grenada',
    code: "308"
  }, {
    country: 'Guadeloupe',
    code: "312"
  }, {
    country: 'Guam',
    code: "316"
  }, {
    country: 'Guatemala',
    code: "320"
  }, {
    country: 'Guernsey',
    code: "831"
  }, {
    country: 'Guinea',
    code: "324"
  }, {
    country: 'Guinea-Bissau',
    code: "624"
  }, {
    country: 'Guyana',
    code: "328"
  }, {
    country: 'Haiti',
    code: "332"
  }, {
    country: 'HeardandMcdonaldIslands',
    code: "334"
  }, {
    country: 'HolySee',
    code: "336"
  }, {
    country: 'Honduras',
    code: "340"
  }, {
    country: 'Hungary',
    code: "348"
  }, {
    country: 'Iceland',
    code: "352"
  }, {
    country: 'India',
    code: "356"
  }, {
    country: 'Indonesia',
    code: "360"
  }, {
    country: 'Iran,IslamicRepublicof',
    code: "364"
  }, {
    country: 'Iraq',
    code: "368"
  }, {
    country: 'Ireland',
    code: "372"
  }, {
    country: 'IsleofMan',
    code: "833"
  }, {
    country: 'Israel',
    code: "376"
  }, {
    country: 'Italy',
    code: "380"
  }, {
    country: 'Jamaica',
    code: "388"
  }, {
    country: 'Japan',
    code: "392"
  }, {
    country: 'Jersey',
    code: "832"
  }, {
    country: 'Jordan',
    code: "400"
  }, {
    country: 'Kazakhstan',
    code: "398"
  }, {
    country: 'Kenya',
    code: "404"
  }, {
    country: 'Kiribati',
    code: "296"
  }, {
    country: 'Korea',
    code: "408"
  }, {
    country: 'Korea',
    code: "410"
  }, {
    country: 'Kuwait',
    code: "414"
  }, {
    country: 'Kyrgyzstan',
    code: "417"
  }, {
    country: 'LaoPDR',
    code: "418"
  }, {
    country: 'Latvia',
    code: "428"
  }, {
    country: 'Lebanon',
    code: "422"
  }, {
    country: 'Lesotho',
    code: "426"
  }, {
    country: 'Liberia',
    code: "430"
  }, {
    country: 'Libya',
    code: "434"
  }, {
    country: 'Liechtenstein',
    code: "438"
  }, {
    country: 'Lithuania',
    code: "440"
  }, {
    country: 'Luxembourg',
    code: "442"
  }, {
    country: 'Macedonia,Republicof',
    code: "807"
  }, {
    country: 'Madagascar',
    code: "450"
  }, {
    country: 'Malawi',
    code: "454"
  }, {
    country: 'Malaysia',
    code: "458"
  }, {
    country: 'Maldives',
    code: "462"
  }, {
    country: 'Mali',
    code: "466"
  }, {
    country: 'Malta',
    code: "470"
  }, {
    country: 'MarshallIslands',
    code: "584"
  }, {
    country: 'Martinique',
    code: "474"
  }, {
    country: 'Mauritania',
    code: "478"
  }, {
    country: 'Mauritius',
    code: "480"
  }, {
    country: 'Mayotte',
    code: "175"
  }, {
    country: 'Mexico',
    code: "484"
  }, {
    country: 'Micronesia,FederatedStatesof',
    code: "583"
  }, {
    country: 'Moldova',
    code: "498"
  }, {
    country: 'Monaco',
    code: "492"
  }, {
    country: 'Mongolia',
    code: "496"
  }, {
    country: 'Montenegro',
    code: "499"
  }, {
    country: 'Montserrat',
    code: "500"
  }, {
    country: 'Morocco',
    code: "504"
  }, {
    country: 'Mozambique',
    code: "508"
  }, {
    country: 'Myanmar',
    code: "104"
  }, {
    country: 'Namibia',
    code: "516"
  }, {
    country: 'Nauru',
    code: "520"
  }, {
    country: 'Nepal',
    code: "524"
  }, {
    country: 'Netherlands',
    code: "528"
  }, {
    country: 'NetherlandsAntilles',
    code: "530"
  }, {
    country: 'NewCaledonia',
    code: "540"
  }, {
    country: 'NewZealand',
    code: "554"
  }, {
    country: 'Nicaragua',
    code: "558"
  }, {
    country: 'Niger',
    code: "562"
  }, {
    country: 'Nigeria',
    code: "566"
  }, {
    country: 'Niue',
    code: "570"
  }, {
    country: 'NorfolkIsland',
    code: "574"
  }, {
    country: 'NorthernMarianaIslands',
    code: "580"
  }, {
    country: 'Norway',
    code: "578"
  }, {
    country: 'Oman',
    code: "512"
  }, {
    country: 'Pakistan',
    code: "586"
  }, {
    country: 'Palau',
    code: "585"
  }, {
    country: 'PalestinianTerritory',
    code: "275"
  }, {
    country: 'Panama',
    code: "591"
  }, {
    country: 'PapuaNewGuinea',
    code: "598"
  }, {
    country: 'Paraguay',
    code: "600"
  }, {
    country: 'Peru',
    code: "604"
  }, {
    country: 'Philippines',
    code: "608"
  }, {
    country: 'Pitcairn',
    code: "612"
  }, {
    country: 'Poland',
    code: "616"
  }, {
    country: 'Portugal',
    code: "620"
  }, {
    country: 'PuertoRico',
    code: "630"
  }, {
    country: 'Qatar',
    code: "634"
  }, {
    country: 'Romania',
    code: "642"
  }, {
    country: 'RussianFederation',
    code: "643"
  }, {
    country: 'Rwanda',
    code: "646"
  }, {
    country: 'SaintHelena',
    code: "654"
  }, {
    country: 'SaintKittsandNevis',
    code: "659"
  }, {
    country: 'SaintLucia',
    code: "662"
  }, {
    country: 'Saint-Martin(Frenchpart)',
    code: "663"
  }, {
    country: 'SaintPierreandMiquelon',
    code: "666"
  }, {
    country: 'SaintVincentandGrenadines',
    code: "670"
  }, {
    country: 'Samoa',
    code: "882"
  }, {
    country: 'SanMarino',
    code: "674"
  }, {
    country: 'SaoTomeandPrincipe',
    code: "678"
  }, {
    country: 'SaudiArabia',
    code: "682"
  }, {
    country: 'Senegal',
    code: "686"
  }, {
    country: 'Serbia',
    code: "688"
  }, {
    country: 'Seychelles',
    code: "690"
  }, {
    country: 'SierraLeone',
    code: "694"
  }, {
    country: 'Singapore',
    code: "702"
  }, {
    country: 'Slovakia',
    code: "703"
  }, {
    country: 'Slovenia',
    code: "705"
  }, {
    country: 'SolomonIslands',
    code: "090"
  }, {
    country: 'Somalia',
    code: "706"
  }, {
    country: 'SouthAfrica',
    code: "710"
  }, {
    country: 'SouthGeorgiaandtheSouthSandwichIslands',
    code: "239"
  }, {
    country: 'SouthSudan',
    code: "728"
  }, {
    country: 'Spain',
    code: "724"
  }, {
    country: 'SriLanka',
    code: "144"
  }, {
    country: 'Sudan',
    code: "736"
  }, {
    country: 'Suriname',
    code: "740"
  }, {
    country: 'SvalbardandJanMayenIslands',
    code: "744"
  }, {
    country: 'Swaziland',
    code: "748"
  }, {
    country: 'Sweden',
    code: "752"
  }, {
    country: 'Switzerland',
    code: "756"
  }, {
    country: 'SyrianArabRepublic',
    code: "760"
  }, {
    country: 'Taiwan',
    code: "158"
  }, {
    country: 'Tajikistan',
    code: "762"
  }, {
    country: 'Tanzania',
    code: "834"
  }, {
    country: 'Thailand',
    code: "764"
  }, {
    country: 'Timor-Leste',
    code: "626"
  }, {
    country: 'Togo',
    code: "768"
  }, {
    country: 'Tokelau',
    code: "772"
  }, {
    country: 'Tonga',
    code: "776"
  }, {
    country: 'TrinidadandTobago',
    code: "780"
  }, {
    country: 'Tunisia',
    code: "788"
  }, {
    country: 'Turkey',
    code: "792"
  }, {
    country: 'Turkmenistan',
    code: "795"
  }, {
    country: 'TurksandCaicosIslands',
    code: "796"
  }, {
    country: 'Tuvalu',
    code: "798"
  }, {
    country: 'Uganda',
    code: "800"
  }, {
    country: 'Ukraine',
    code: "804"
  }, {
    country: 'UnitedArabEmirates',
    code: "784"
  }, {
    country: 'UnitedKingdom',
    code: "826"
  }, {
    country: 'UnitedStatesofAmerica',
    code: "840"
  }, {
    country: 'USMinorOutlyingIslands',
    code: "581"
  }, {
    country: 'Uruguay',
    code: "858"
  }, {
    country: 'Uzbekistan',
    code: "860"
  }, {
    country: 'Vanuatu',
    code: "548"
  }, {
    country: 'Venezuela',
    code: "862"
  }, {
    country: 'VietNam',
    code: "704"
  }, {
    country: 'VirginIslands,US',
    code: "850"
  }, {
    country: 'WallisandFutunaIslands,US',
    code: "876"
  }, {
    country: 'WesternSahara,US',
    code: "732"
  }, {
    country: 'Yemen',
    code: "887"
  }, {
    country: 'Zambia',
    code: "894"
  }, {
    country: 'Zimbabwe',
    code: "716"
  }
]
